sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-036.pdf --upload --lsstdoc DMTN-036.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="dmtn-036"
    # Add LSST the Docs credentials
    - secure: "Pgpo/PgMi0zJyFk0oS2O2OCvqhirmhBs7bykhUvUEPAAk3n8mum+knHakbGVZ4Eq1kE/7UxrSa041h9ra9/8PmoaPIOZtF2nEB4sQjHzuPj7pSBPJxsHcOaDDkQUqyCUPM4meP3ZsSxw7TXMVDaMMNMb0y3gJMPFac6mZsTj/+Rqx9Z+DUms60REZZ4Yy1AXRRPKsja5SCR1JEbgSVmJv2csETQokpZU+2bbdAR7LguokYwovpwl/djJjfKiorLvbxE1DLdq1HFef/Fui6jfSsQWzAS+Pf6859YCMdUQO62BGIq20ZASHBxqEmBhlpLJesUOYVJfPuWIU03pKrmotoXxIFthlaM3fvoBKwj1EPyEu2WAhLWwOSSuGHELMYw9F2KVHKByASU/U2KKbeed178XR95qn4B7SXvOUciU+6PZiB4KQbvY8FRHS/pGT0dkP2JhxEeVCZ029I4xgrgl0ON7hesu5MfVTik82cwDywFQ4kLs2aKJBxydNZrUUP6U60inYOKMEPdi2gG2LxpaBt/VuG437b7V7ck/r5YvKc3tENxvP+/Rv7g5cd7I45w+377fAKzaahZ2xc8o+SDI0AJLyqNgxL3ySSdpjUDt6KSheRsjUIPYSgArrBjWpiy2P3FORIu65ahBRDbz1OGLqAECYLC9EDAJ4S8f/n4OwPM="
    - secure: "SyXEDFEZ2PF0hDAAELOaNFFyZmvQeLyw8b/APvVw/2R0yQbFauaGyllXZbCFD4wvF10tr9z1Gs/fSbD/Nxh7H/MYljwgOAMdXyBvIEUpzicsYux3TILYalluhSBhTTxu5mc1lJcSODT1pJUZ8hJe07QWowFLofFBnr6D8293tT0YynaPd5WoYeRiZiTcJD8bsYAkj5jzzoL26LdNY6rhUpAOoxI+CnOxD+spfduEgMSONr2u8ZXonkmTz8YZnFK1uJJq9RTPsoEAqrNRloR4lwvsDVYQkPxD9jof5BwCeslvFq9TFrZo5hEE8wQhVBIVP9iuXvDy6xTzcY8CWWM6EvKw75N4JX9gogE0KTvHxlLwxwpz5lTkro+P9fL9oLxICbR64DN9hF9V8VxZ7GCCKx7oPUvSTKxs0PTbAdx4ly2UqKq3HHZlX+ohiDYRiXwk0OoB5ur0dl6aUEOij8u/b8H+YHbg774DOcasvoZ8sGHj4xztYl3ICGiCdgEJ3bskX1nU+yrYlCaAuAT6WlfeOtKNvWFzAgKtjxMHvOD4fmt88S16uCquZZ91idDCSM8tqne42k3FtbSEt3L16owYFz1w6XODwgz3TiXG6yDHl8lXaTFYBZPAnrqeAnRk2sNyuE/ZPqgdvgAU6NTcnzOWyRq24zerp4ZwdTpn+3rQDS4="
